services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - proxy
    dns: 
      - 172.22.20.1
      - 8.8.8.8
    hostname: prowlarr
    volumes:
      - ./config:/config
      - /media:/media
      - /downloads:/downloads
      - /downloads:/download
    environment:
      - APP_GROUP=Requests
      - APP_LOGO=https://static-00.iconduck.com/assets.00/prowlarr-icon-2048x2048-2pxvehfe.png
      - VIRTUAL_HOST=prowlarr.admin.pknw1.co.uk
      - VIRTUAL_PORT=9696
      

networks:
  proxy:
    external: true

